{ textChannel:
    TextChannel {
      type: 'text',
      deleted: false,
      id: '751391438024998973',
      name: 'music',
      rawPosition: 2,
      parentID: '721457525559525429',
      permissionOverwrites: Collection [Map] {},
      topic: null,
      nsfw: undefined,
      lastMessageID: '751808630386589777',
      rateLimitPerUser: 0,
      lastPinTimestamp: null,
      guild:
       Guild {
         members: [GuildMemberManager],
         channels: [GuildChannelManager],
         roles: [RoleManager],
         presences: [PresenceManager],
         voiceStates: [VoiceStateManager],
         deleted: false,
         available: true,
         id: '721457525559525427',
         shardID: 0,
         name: 'Arnav\'s server',
         icon: null,
         splash: null,
         region: 'india',
         memberCount: 4,
         large: false,
         features: [],
         applicationID: null,
         afkTimeout: 300,
         afkChannelID: null,
         systemChannelID: '721457525559525430',
         embedEnabled: undefined,
         premiumTier: 0,
         premiumSubscriptionCount: 0,
         verificationLevel: 'NONE',
         explicitContentFilter: 'DISABLED',
         mfaLevel: 0,
         joinedTimestamp: 1599210555203,
         defaultMessageNotifications: 'ALL',
         systemChannelFlags: [SystemChannelFlags],
         vanityURLCode: null,
         description: null,
         banner: null,
         rulesChannelID: null,
         publicUpdatesChannelID: null,
         ownerID: '455659642983415821',
         emojis: [GuildEmojiManager] },
      messages:
       MessageManager {
         cacheType: [Function: LimitedCollection],
         cache: [LimitedCollection],
         channel: [Circular] },
      _typing: Map { '455659642983415821' => [Object] } },
   voiceChannel:
    VoiceChannel {
      type: 'voice',
      deleted: false,
      id: '751304617576628225',
      name: 'test1',
      rawPosition: 1,
      parentID: '721457525559525429',
      permissionOverwrites: Collection [Map] {},
      bitrate: 64000,
      userLimit: 0,
      guild:
       Guild {
         members: [GuildMemberManager],
         channels: [GuildChannelManager],
         roles: [RoleManager],
         presences: [PresenceManager],
         voiceStates: [VoiceStateManager],
         deleted: false,
         available: true,
         id: '721457525559525427',
         shardID: 0,
         name: 'Arnav\'s server',
         icon: null,
         splash: null,
         region: 'india',
         memberCount: 4,
         large: false,
         features: [],
         applicationID: null,
         afkTimeout: 300,
         afkChannelID: null,
         systemChannelID: '721457525559525430',
         embedEnabled: undefined,
         premiumTier: 0,
         premiumSubscriptionCount: 0,
         verificationLevel: 'NONE',
         explicitContentFilter: 'DISABLED',
         mfaLevel: 0,
         joinedTimestamp: 1599210555203,
         defaultMessageNotifications: 'ALL',
         systemChannelFlags: [SystemChannelFlags],
         vanityURLCode: null,
         description: null,
         banner: null,
         rulesChannelID: null,
         publicUpdatesChannelID: null,
         ownerID: '455659642983415821',
         emojis: [GuildEmojiManager] } },
   connection:
    VoiceConnection {
      _events:
       [Object: null prototype] {
         closing: [Array],
         debug: [Function],
         failed: [Function],
         disconnect: [Function] },
      _eventsCount: 4,
      _maxListeners: undefined,
      voiceManager:
       ClientVoiceManager { connections: [Collection], broadcasts: [] },
      channel:
       VoiceChannel {
         type: 'voice',
         deleted: false,
         id: '751304617576628225',
         name: 'test1',
         rawPosition: 1,
         parentID: '721457525559525429',
         permissionOverwrites: Collection [Map] {},
         bitrate: 64000,
         userLimit: 0,
         guild: [Guild] },
      status: 0,
      speaking: Speaking { bitfield: 0 },
      authentication:
       { sessionID: 'bc5b7ab0babb93d60307c0136a154f5d',
         token: '14ec7417464a31b3',
         endpoint: 'india97.discord.media',
         ssrc: 28653250,
         port: 50001,
         modes: [Array],
         ip: '43.251.180.62',
         experiments: [Array],
         mode: 'xsalsa20_poly1305_lite',
         video_codec: null,
         secret_key: [Uint8Array],
         media_session_id: '4b0c6916363fac4052188656a4ee4ca4',
         encodings: [Array],
         audio_codec: 'opus' },
      player:
       AudioPlayer {
         _events: [Object],
         _eventsCount: 2,
         _maxListeners: undefined,
         dispatcher: null,
         streamingData: [Object],
         voiceConnection: [Circular] },
      ssrcMap: Map { 28653247 => '455659642983415821' },
      _speaking: Map {},
      sockets: { ws: [VoiceWebSocket], udp: [VoiceConnectionUDPClient] },
      receiver:
       VoiceReceiver {
         _events: [Object: null prototype] {},
         _eventsCount: 0,
         _maxListeners: undefined,
         connection: [Circular],
         packets: [PacketHandler] },
      connectTimeout:
       Timeout {
         _called: false,
         _idleTimeout: -1,
         _idlePrev: null,
         _idleNext: null,
         _idleStart: 16729,
         _onTimeout: null,
         _timerArgs: undefined,
         _repeat: null,
         _destroyed: false,
         [Symbol(unrefed)]: false,
         [Symbol(asyncId)]: 5074,
         [Symbol(triggerId)]: 0 } },
   songs:
    [ { title: 'Game of Thrones - The Rains Of Castamere | by The National',
        url: 'https://www.youtube.com/watch?v=ECewrAld3zw' } ],
   volume: 5,
   playing: true }
